#include "DataFormats/EcalRawData/interface/EcalDCCHeaderBlockHostCollection.h"
#include "DataFormats/Portable/interface/PortableHostCollectionReadRules.h"

SET_PORTABLEHOSTCOLLECTION_READ_RULES(EcalDCCHeaderBlockHostCollection);
